(require 'ido)
(setq ido-show-dot-for-dired t)
(setq ido-use-filename-at-point 'guess)
(setq ido-create-new-buffer 'always)
(setq-default confirm-nonexistent-file-or-buffer nil)
(define-key ido-file-completion-map (kbd "TAB") 'ido-complete)
(define-key ido-buffer-completion-map (kbd "TAB") 'ido-complete)
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)

(rc/require 'smex 'ido-completing-read+)
(require 'ido-completing-read+)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
(ido-ubiquitous-mode 1)
